apiVersion: app/v1
kind: ReplicaSet
metadata:
    name: replicaset
    labels:
      app: myapp-replicaset
      type: front-end 
spec:
  template:
     metadata:
        name: nginx-osb
        labels:
          env: production
          type: front-end 
     spec:
       containers:
         - name: nginx
           image: nginx    
    
  selector:
     matchLabels:
       type: front-end
    